insert into tense(NAME) VALUES('present simple');
insert into tense(NAME) VALUES('present continuous');
insert into tense(NAME) VALUES('present perfect ');
insert into tense(NAME) VALUES('present perfect continuous');
insert into tense(NAME) VALUES('past simple');
insert into tense(NAME) VALUES('past continuous');
insert into tense(NAME) VALUES('past perfect');
insert into tense(NAME) VALUES('past perfect continuous');
insert into tense(NAME) VALUES('future simple');
insert into tense(NAME) VALUES('future continuous');
insert into tense(NAME) VALUES('future perfect');
insert into tense(NAME) VALUES('future perfect continuous');
